### ISSUE TITLE
Resolve: Update container errors

### ISSUE THREAD

**Issue by tokejepsen** [ynput/ayon-core#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Updating a container in the manager errors with:
```
Traceback (most recent call last):
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 236, in <lambda>
    lambda: self._update_containers(items, version=-1)
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 819, in _update_containers
    update_container(item, item_version)
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\pipeline\load\utils.py", line 517, in update_container
    return Loader().update(container, context)
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\hosts\resolve\plugins\load\load_clip.py", line 82, in update
    self.set_item_color(timeline_item, version=context["version"])
  File "C:\Users\tokejepsen\ayon-core\client\ayon_core\hosts\resolve\plugins\load\load_clip.py", line 130, in set_item_color
    version["parent"],
KeyError: 'parent'
```

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load a clip (EXR) into a timeline in Resolve.
2. Switch version in the Manager.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
Shouldn't `parent` key always be present on version data?

**Comment by BigRoy** [comment]
The issue is [here](https://github.com/ynput/ayon-core/pull/130/files#diff-56ab238555db3314a6d7c021fbc1f62198f4c177c2cfc90477de52cdcba36e92R468-R484)

Those queries filter `fields` but we want to pass the _full_ context to the `Loader.update` calls.

Bug was introduced with #130 indeed.

**Comment by jakubjezek001** [comment]
hey @tokejepsen I believe this had been fixed already. Can you try again please?

**Comment by tokejepsen** [comment]
> hey @tokejepsen I believe this had been fixed already. Can you try again please?

Nice, resolved!
