### ISSUE TITLE
Workfiles: Saving artist note workfile_info id error

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

In workfiles tool when saving an artist note I sometimes get this error:

```
# Traceback (most recent call last):
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\widgets\side_panel.py", line 107, in _on_save_click
#     self._controller.save_workfile_info(
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\control.py", line 448, in save_workfile_info
#     self._workfiles_model.save_workfile_info(
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\models\workfiles.py", line 702, in save_workfile_info
#     self._entities_model.save_workfile_info(
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\models\workfiles.py", line 547, in save_workfile_info
#     workfile_info["id"],
# KeyError: 'id'
```

It does seem to save the note - but it does error.

### Expected Behavior:

No errors.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Open Workfile tool
2. Press "Save As" to create a new save.
3. For the new workfile, save an artist note.

(Tested in Maya 2024)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
# Traceback (most recent call last):
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\widgets\side_panel.py", line 107, in _on_save_click
#     self._controller.save_workfile_info(
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\control.py", line 448, in save_workfile_info
#     self._workfiles_model.save_workfile_info(
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\models\workfiles.py", line 702, in save_workfile_info
#     self._entities_model.save_workfile_info(
#   File "E:\dev\ayon-core\client\ayon_core\tools\workfiles\models\workfiles.py", line 547, in save_workfile_info
#     workfile_info["id"],
# KeyError: 'id'
```

**Comment by BigRoy** [comment]
This was fixed with https://github.com/ynput/ayon-core/pull/647

This issue was also reported on discord [here](https://discord.com/channels/517362899170230292/517382145552154634/1250474895658188871)
