### ISSUE TITLE
Maya: ReferenceLoader update failure due to no reference node reports wrong message

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Whenever you have a Maya scene that has loaded containers of `ReferenceLoader` using maya references, but for whatever reason the Maya Reference node does not exist anymore yet the container is still lingering around. When trying to update this error occurs:
```python
// Warning: SceneInventory : Update failed
// Traceback (most recent call last):
//   File "E:\dev\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 822, in _update_containers
//     update_container(item, item_version)
//   File "E:\dev\ayon-core\client\ayon_core\pipeline\load\utils.py", line 532, in update_container
//     return Loader().update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_reference.py", line 266, in update
//     super(ReferenceLoader, self).update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\plugin.py", line 890, in update
//     reference_node = lib.get_reference_node(members, self.log)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\lib.py", line 4288, in get_reference_node
//     assert references, "No reference node found in container"
// AssertionError: No reference node found in container
```

However, this dialog shows to the user:
![image](https://github.com/ynput/ayon-core/assets/2439881/86b94ec7-6f29-44e2-b22e-e9d53040d69e)

The message is incorrect since the version being updated to exists just fine.

### Expected Behavior:

The displayed message to the artist should be correct.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load a Maya reference
2. In outliner enable > Display > Ignore "Hidden in outliner"
3. In `AVALON_CONTAINERS` add an object into the reference container (just so that maya does not auto-delete it in next step)
4. On the loaded maya reference remove the reference (via Maya itself, not via AYON tools)
5. Container object set should still exist, but no reference node
6. Via Ayon > Manage.. try to set the version of the container - it will fail.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
// Warning: SceneInventory : Update failed
// Traceback (most recent call last):
//   File "E:\dev\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 822, in _update_containers
//     update_container(item, item_version)
//   File "E:\dev\ayon-core\client\ayon_core\pipeline\load\utils.py", line 532, in update_container
//     return Loader().update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_reference.py", line 266, in update
//     super(ReferenceLoader, self).update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\plugin.py", line 890, in update
//     reference_node = lib.get_reference_node(members, self.log)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\lib.py", line 4288, in get_reference_node
//     assert references, "No reference node found in container"
// AssertionError: No reference node found in container
```

**Comment by BigRoy** [comment]
Changing the code from `assert` to `raise LoadError("..")` does resolve the wrong dialog being displayed, however that displays no pop-up dialog at all which seems to be [due to the code here](https://github.com/ynput/ayon-core/blob/ccc3c1710acda86eeaf4840a88384f127c55f549/client/ayon_core/tools/sceneinventory/view.py#L820-L825).

Should we implement a `LoadError` exception there @iLLiCiTiT ?

**Comment by BigRoy** [comment]
I suppose we make a dedicated exception for the `RepresentationNotExists` to get that dialog only when we know it is the case and otherwise show a less dedicated dialog with just a stack trace, but I'm not sure where those dialogs are hidden in the codebase to easily show those.
