### ISSUE TITLE
Nuke Studio can't load clips via loader

### ISSUE THREAD

**Issue by DeBontDigital** [ynput/ayon-core#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

![image](https://github.com/ynput/ayon-core/assets/101574781/96e293ff-2344-4511-ac93-d57c102f3ab5)
When I want to load published clips in my timeline I keep getting this error. I'm on Nuke 15.0. 
This happens on exrs and reviewables. 

### Expected Behavior:

https://www.youtube.com/watch?v=5Wd6X-71vbg

I would expect this behaviour that is presented in the youtube tutorial. 

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Create a Nuke Studio file
2. Create a published clip
3. open it in NukeX, render new version, publish that version
4. Load it in Nuke Studio, -> error.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
During load error happened on Product: "renderCompositingMain" Representation: "exr" Version: 2

Error message: 'families'

Traceback (most recent call last):
  File "C:\Users\Remco\AppData\Local\Ynput\AYON\addons\core_0.3.1\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\Users\Remco\AppData\Local\Ynput\AYON\addons\core_0.3.1\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Users\Remco\AppData\Local\Ynput\AYON\addons\core_0.3.1\ayon_core\hosts\hiero\plugins\load\load_clip.py", line 91, in load
    track_item = phiero.ClipLoader(self, context, path, **options).load()
  File "C:\Users\Remco\AppData\Local\Ynput\AYON\addons\core_0.3.1\ayon_core\hosts\hiero\api\plugin.py", line 553, in load
    slate_on = "slate" in self.context["version"]["data"]["families"]
KeyError: 'families'
```

**Comment by m-u-r-p-h-y** [comment]
did you try with the latest ayon_core 0.4.0 ?

**Comment by DeBontDigital** [comment]
> did you try with the latest ayon_core 0.4.0 ?

... Didn't saw 0.4.0 in the market. After a manual update it fixed it. Thanks for the quick reply!!
