### ISSUE TITLE
Representation context UDIM value is stored as `list` on integration instead of `str`

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When integrating UDIM textures from Substance Painter the `udim` key-value used in the paths formatting for the [representation gets stored as a list](https://github.com/ynput/ayon-core/blob/f6e3dcb4742e083664744de016476d8c134f5ef0/client/ayon_core/plugins/publish/integrate.py#L792-L795) which seems "wrong" but apparently I did this originally here https://github.com/ynput/OpenPype/pull/2898 but can't think of why I did that.

This is an example content of `representation_entity["context"]` on load:
```python
{"ext": "png",
 "root": {
     "work": "D: / sh_boss_proj",
     "renders": "D: / sh_boss_proj / ue_renders"},
 "task": {
     "name": "art",
     "type": "Art",
     "short": "art"},
 "udim": [
     "1001"],
 "user": "admin",
 "asset": "asset",
 "family": "image",
 "folder": {
     "name": "asset",
     "path": "/lenny_bedroom/asset",
     "type": "Asset"},
 "subset": "textureMain.Bread.Color",
 "product": {
     "name": "textureMain.Bread.Color",
     "type": "image"},
 "project": {
     "code": "il",
     "name": "interior_lenny"},
 "version": 5,
 "username": "admin",
 "hierarchy": "lenny_bedroom",
 "representation": "png"}
```

@iLLiCiTiT any reason you may think of?

---

This currently breaks updating/managing representations that were published this way. E.g. loading substance painter UDIM tiles into file nodes in Maya and updating them:

```python
utils context: {'ext': 'png', 'root': {'work': 'D:/sh_boss_proj'}, 'task': {'name': 'art', 'type': 'Art', 'short': 'art'}, 'udim': ['1001'], 'user': 'admin', 'asset': 'asset', 'family': 'image', 'folder': {'name': 'asset', 'path': '/lenny_bedroom/asset', 'type': 'Asset'}, 'subset': 'textureMain.Bread.Color', 'product': {'name': 'textureMain.Bread.Color', 'type': 'image'}, 'project': {'code': 'il', 'name': 'interior_lenny'}, 'version': 4, 'username': 'admin', 'hierarchy': 'lenny_bedroom', 'representation': 'png'}
# Traceback (most recent call last):
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 366, in <lambda>
#     lambda: self._show_version_dialog(item_ids, active_repre_id)
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 843, in _show_version_dialog
#     self._update_containers_to_version(
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1032, in _update_containers_to_version
#     self._update_containers(item_ids, versions)
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1007, in _update_containers
#     update_container(container, item_version)
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\pipeline\load\utils.py", line 521, in update_container
#     raise ValueError("Path {} doesn't exist".format(path))
# ValueError: Path D:/sh_boss_proj/interior_lenny/lenny_bedroom/asset/publish/image/textureMain.Bread.Color/v004/il_asset_textureMain.Bread.Color_v004.png doesn't exist
```
OR
```python
# Traceback (most recent call last):
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 366, in <lambda>
#     lambda: self._show_version_dialog(item_ids, active_repre_id)
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 843, in _show_version_dialog
#     self._update_containers_to_version(
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1032, in _update_containers_to_version
#     self._update_containers(item_ids, versions)
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1007, in _update_containers
#     update_container(container, item_version)
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\pipeline\load\utils.py", line 521, in update_container
#     raise ValueError("Path {} doesn't exist".format(path))
# ValueError: Path D:/sh_boss_proj/interior_lenny/lenny_bedroom/asset/publish/image/textureMain.TablewareTransparent.Color/v004/il_asset_textureMain.TablewareTransparent.Color_v004.png doesn't exist
```

### Expected Behavior:

As far as I know the representation entity's `context` should contain key-values that are exactly what was used to format the representations (first file) path. Hence, it should be the first UDIM tile number as a string, not a list.

---

Technically this could also be resolved by removing the "file exists" check on the api `update_container` call but I think we'd just be shadowing/avoiding a thing that's actually still a bug. so we'd better fix it in the Integrator.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Publish textures with UDIM from Substance Painter
2. Load to file node in Maya
3. Update the file node (or set version) from scene inventory

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
# Traceback (most recent call last):
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 366, in <lambda>
#     lambda: self._show_version_dialog(item_ids, active_repre_id)
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 843, in _show_version_dialog
#     self._update_containers_to_version(
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1032, in _update_containers_to_version
#     self._update_containers(item_ids, versions)
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1007, in _update_containers
#     update_container(container, item_version)
#   File "D:\kayla_ayon_core\ayon-core\client\ayon_core\pipeline\load\utils.py", line 521, in update_container
#     raise ValueError("Path {} doesn't exist".format(path))
# ValueError: Path D:/sh_boss_proj/interior_lenny/lenny_bedroom/asset/publish/image/textureMain.TablewareTransparent.Color/v004/il_asset_textureMain.TablewareTransparent.Color_v004.png doesn't exist
```

**Comment by BigRoy** [comment]
Fixed by https://github.com/ynput/ayon-core/pull/764
