### ISSUE TITLE
`Extract OIIO Transcode` wrong filtering

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-core#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

I hit an issue with `Extract OIIO Transcode` filtering where it didn't work as expected. (or maybe I missed something, IDK)
The plugin didn't work with AOVs in Houdini. 

Here's a snippet of my settings

![image](https://github.com/user-attachments/assets/2c5d6e60-66a4-4683-ac94-df69c567e92e)

---

[This plugin](https://github.com/BigRoy/ayon-houdini/blob/69250cbd858f506659e76ac701bc3613af2924e7/client/ayon_houdini/plugins/publish/collect_render_colorspace.py#L13-L20) should applies the following filter which adds `review` tag.
![image](https://github.com/user-attachments/assets/ccc41c04-5348-4c12-89b0-baf398c82f1b)

but based on my profile configuration, `Extract OIIO Transcode` should pick only the instance with `"render"` product type and tag `["review"]`. the beauty AOV is the only one that should pass the filter as other instances don't have a `review` tag. 

![image](https://github.com/user-attachments/assets/e5ed6edc-da41-4233-b52b-4e323b89c89e)

And when they don't have a review tag, they will most likely fail because of no proper channel to convert.
```python
Traceback (most recent call last):
  File "C:\Users\Mustafa Taher\AppData\Local\Ynput\AYON\dependency_packages\ayon_2408011901_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "E:\Ynput\ayon-core\client\ayon_core\plugins\publish\extract_color_transcode.py", line 157, in process
    convert_colorspace(
  File "E:\Ynput\ayon-core\client\ayon_core\lib\transcoding.py", line 1141, in convert_colorspace
    input_arg, channels_arg = get_oiio_input_and_channel_args(input_info)
  File "E:\Ynput\ayon-core\client\ayon_core\lib\transcoding.py", line 1432, in get_oiio_input_and_channel_args
    raise ValueError(
ValueError: Couldn't find channels that can be used for conversion.
```

### Expected Behavior:

The plugin should skip the instance if the specified tag doesn't exist.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Enable `Extract OIIO Transcode`
2. Publish Render from Houdini with multiple AOVs (raise Error)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
@MustafaJafar how relevant is this still - and if relevant, can you provide more info about whether anything has changed?

**Comment by MustafaJafar** [comment]
> [@MustafaJafar](https://github.com/MustafaJafar) how relevant is this still - and if relevant, can you provide more info about whether anything has changed?

I'll give it another test and report back.

**Comment by MustafaJafar** [comment]
I can't replicate the issue. 
I believe the issue here was trying to convert not supported channels. which I think was solved in #1542 if I'm not mistaken.

<img width="706" height="209" alt="Image" src="https://github.com/user-attachments/assets/d9ee7a32-845e-43e8-ba05-002cd8c190e4" />


Also, it shows an issue that my regex list is too generic 😝 which captured the P aov as well 😆 

<img width="1469" height="394" alt="Image" src="https://github.com/user-attachments/assets/a4a33c6a-06b6-46e8-8b3a-89b2db2dbfce" />
